const programs = [
  {
    id: "soccer",
    name: "Intro to Soccer",
    category: "Sports",
    ageLabel: "6 - 8",
    ageMin: 6,
    ageMax: 8,
    location: "City Sports Field",
    day: "Saturday",
    time: "10:00 AM",
    price: 85,
    image: "images/soccer-small.png",
    imageLarge: "images/soccer-large.png",
    imageAlt: "Children playing soccer outdoors",
    tagline: "Learn the basics and have fun!",
    description: "Intro to Soccer introduces children to basic soccer skills through fun games, teamwork, and beginner-friendly drills. This program helps young players build confidence, coordination, and a love for staying active."
  },
  {
    id: "swim",
    name: "Swim Lessons",
    category: "Swimming",
    ageLabel: "4+",
    ageMin: 4,
    ageMax: 99,
    location: "Ottawa Rec Centre",
    day: "Tuesday",
    time: "5:30 PM",
    price: 50,
    image: "images/swimming-small.png",
    imageLarge: "images/swimming-large.png",
    imageAlt: "Children attending a swimming lesson",
    tagline: "Build skills and confidence in the water.",
    description: "Swim Lessons offer a safe and supportive environment for swimmers of all ages to learn fundamental swimming skills and water safety. Classes are grouped by age and skill level, so everyone from young children to adults can build confidence in the water at their own pace."
  },
  {
    id: "youth-basketball",
    name: "Youth Basketball",
    category: "Sports",
    ageLabel: "9 - 12",
    ageMin: 9,
    ageMax: 12,
    location: "Ottawa Rec Centre",
    day: "Wednesday",
    time: "6:00 PM",
    price: 60,
    image: "images/basketball-small.png",
    imageLarge: "images/basketball-large.png",
    imageAlt: "Children playing basketball indoors",
    tagline: "Learn the fundamentals of basketball.",
    description: "Youth Basketball focuses on teaching children the fundamentals of basketball, including dribbling, shooting, passing, and teamwork. This program encourages physical activity and sportsmanship."
  },
  {
    id: "dance",
    name: "Dance",
    category: "Dance",
    ageLabel: "55+",
    ageMin: 55,
    ageMax: 99,
    location: "Ottawa Rec Centre",
    day: "Thursday",
    time: "1:00 PM",
    price: 45,
    image: "images/dance-small.png",
    imageLarge: "images/dance-large.png",
    imageAlt: "Older adults participating in a dance class",
    tagline: "Move, connect, and have fun.",
    description: "Dance for 55+ offers a welcoming, low-impact class for older adults to enjoy music and movement. Participants explore a variety of dance styles at a comfortable pace while improving balance, flexibility, and coordination, and connecting with others in the community."
  },
  {
    id: "yoga",
    name: "Yoga",
    category: "Fitness",
    ageLabel: "18+",
    ageMin: 18,
    ageMax: 99,
    location: "Ottawa Rec Centre",
    day: "Monday",
    time: "7:00 PM",
    price: 70,
    image: "images/yoga-small.png",
    imageLarge: "images/yoga-large.png",
    imageAlt: "Adults participating in a yoga class",
    tagline: "Relax, stretch, and strengthen.",
    description: "Yoga for adults is designed to help participants improve flexibility, strength, and mental well-being through guided yoga practices. Suitable for all levels, this program promotes relaxation and mindfulness." 
  },
  {
    id: "fitness",
    name: "Fitness",
    category: "Fitness",
    ageLabel: "18+",
    ageMin: 18,
    ageMax: 99,
    location: "Ottawa Rec Centre",
    day: "Daily",
    time: "6:00 PM",
    price: 100,
    image: "images/fitness-small.png",
    imageLarge: "images/fitness-large.png",
    imageAlt: "Adults lifting weights in a gym",
    tagline: "Get fit and have fun!",
    description: "Fitness is a high-energy, results-driven program that combines cardio, strength training, and team-building exercises. Perfect for those looking to improve their fitness and meet new people."
  },
];

function shortDay(day) {
  if (day === "Daily") {
    return day;
  }
  return day.slice(0, 3);
}